# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: UI - Angular CI

on:
  push:
    branches: [master, dev, disaster-rec]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=sha_short;]$(echo $(git rev-parse --short HEAD))"
        id: extract_branch
      - name: Set Constants
        id: consts
        run: |
          echo ::set-output name=repo::$(echo ${GITHUB_REPOSITORY})
          echo ::set-output name=sha_short::$(git rev-parse --short HEAD)
          echo ::set-output name=image-name::$(echo quay.io/neinnovationorg/lrqi-ui})
          echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
          echo ::set-output name=docker_repo::$(echo /neinnovationorg/lrqi-ui)
      - name: Login to Podman
        id: login
        run: |
          echo ${{ steps.extract_branch.outputs.branch }}
          echo ${{ steps.extract_branch.outputs.sha_short }}
          podman login quay.io -u ${{ secrets.docker_username }} -p ${{ secrets.docker_password }}
      - name: Build Image using Podman - AWS
        run: |
          podman build --build-arg CLUSTER=production . -t quay.io/neinnovationorg/lrqi-ui:${{ steps.extract_branch.outputs.branch }} --cgroup-manager=cgroupfs
      - name: Build Image using Podman - Azure
        run: |
          podman build --build-arg CLUSTER=azure . -t quay.io/neinnovationorg/lrqi-ui:${{ steps.extract_branch.outputs.branch }}-azure --cgroup-manager=cgroupfs
      - name: Push Image to Github Registry - AWS
        run: |
          podman push quay.io/neinnovationorg/lrqi-ui:${{ steps.extract_branch.outputs.branch }}
      - name: Push Image to Github Registry - Azure
        run: |
          podman push quay.io/neinnovationorg/lrqi-ui:${{ steps.extract_branch.outputs.branch }}-azure
      - name: OpenShift Action - AWS
        uses: redhat-developer/openshift-actions@v2.0
        with:
          # The URL of the Openshift cluster
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          # JSON with values to connect to the Openshift cluster
          parameters: '{"username": "${{ secrets.OPENSHIFT_USER }}", "acceptUntrustedCerts": "true", "password":"${{ secrets.OPENSHIFT_PASSWORD }}"}'
          # Oc command to be executed
          cmd: |
            'version'
            'project ui-development'
            'tag --source=docker quay.io/neinnovationorg/lrqi-ui:${{ steps.extract_branch.outputs.branch }} ui-development/lrqi-ui:${{ steps.extract_branch.outputs.branch }}'
      - name: OpenShift Action - Azure
        uses: redhat-developer/openshift-actions@v2.0
        with:
          # The URL of the Openshift cluster
          openshift_server_url: ${{ secrets.OPENSHIFT_AZURE_URL }}
          # JSON with values to connect to the Openshift cluster
          parameters: '{"username": "${{ secrets.OPENSHIFT_AZURE_USER }}", "acceptUntrustedCerts": "true", "password":"${{ secrets.OPENSHIFT_AZURE_PASSWORD }}"}'
          # Oc command to be executed
          cmd: |
            'version'
            'project development'
            'tag --source=docker quay.io/neinnovationorg/lrqi-ui:${{ steps.extract_branch.outputs.branch }}-azure development/lrqi-ui:${{ steps.extract_branch.outputs.branch }}'
      - name: Scan Image - AWS
        uses: Azure/container-scan@v0
        continue-on-error: true
        with:
          image-name: quay.io/neinnovationorg/lrqi-ui:${{ steps.extract_branch.outputs.branch }}
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
          token: ${{ github.token }}
          severity-threshold: HIGH
          run-quality-checks: false
      - name: Scan Image - Azure
        uses: Azure/container-scan@v0
        continue-on-error: true
        with:
          image-name: quay.io/neinnovationorg/lrqi-ui:${{ steps.extract_branch.outputs.branch }}-azure
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
          token: ${{ github.token }}
          severity-threshold: HIGH
          run-quality-checks: false
